#!/usr/bin/env bash
# Bootstrap the per-profile Claude Code wiring on a fresh machine.
# Prereq: the dotfiles repo is cloned so ~/.config/claude/{system.md,
# hooks/guard.sh, statusline.sh, agents/, skills/} exist.
# Run ONCE before relying on the guard (it writes settings.json, which the live
# guard's rule 6 would otherwise block).
set -e
H="$HOME"
P="$H/.claude"; R="$H/.claude-reckit"

mkdir -p "$P/agents" "$R/agents" "$P/skills" "$R/skills"
chmod +x "$H/.config/claude/hooks/guard.sh" \
         "$H/.config/claude/statusline.sh" \
         "$H/.config/claude/session-start.sh"

# working-rules.md governs how to reason and report; it lives in the dotfiles so
# it is reproducible, and is symlinked into each profile because CLAUDE.md's @
# includes resolve per-profile.
ln -sf "$H/.config/claude/working-rules.md" "$P/working-rules.md"
ln -sf "$H/.config/claude/working-rules.md" "$R/working-rules.md"

cat > "$P/CLAUDE.md" <<'EOF'
@~/.config/claude/system.md
@~/.claude/working-rules.md

# Profile: PERSONAL
- Active account: **youssefaltai** (`youssef.altai@icloud.com`), Max x20. This is
  the default profile (`~/.claude`). Personal projects live under `~/work/personal/`.
- This subscription also carries noon, dolab-marcom and freelance work — the
  statusline shows `context·profile` so that is never invisible.

# Life context
Durable context about work, clients, people, finances, goals and routines lives
in `~/work/personal/life` (private repo). Read the relevant file there before
asking about something that ought to be already known — contexts are in
`contexts/<name>.md`. Keep it updated when something durable changes.
EOF
cat > "$R/CLAUDE.md" <<'EOF'
@~/.config/claude/system.md
@~/.claude-reckit/working-rules.md

# Profile: RECKIT (work)
- Active account: **youssef-goreckit** (`youssef@goreckit.com`), config dir
  `~/.claude-reckit`. Work lives under `~/work/reckit/`.
- Use the reckit git identity (automatic there), SSH alias `github-reckit`, and
  `GH_CONFIG_DIR=~/.config/gh-reckit` for `gh`.
EOF

# --- settings.json --------------------------------------------------------
# Generated by merging settings.<profile>.json over settings.base.json, then
# substituting __HOME__. Both live in this repo, so settings are reproducible —
# previously settings.json was tracked nowhere and the two profiles had drifted
# apart without anyone noticing.
#
# Note: ~/.claude*/settings.json is deny-listed for agent edits by design, so
# only a human running this script can regenerate them. Existing files are
# backed up first.
gen_settings() {  # $1 = profile delta file
  jq -s 'del(.[]._comment) | .[0] * .[1]' \
     "$H/.config/claude/settings.base.json" "$1" \
   | sed "s|__HOME__|$H|g"
}

write_settings() {  # $1 = target settings.json, $2 = delta file
  local out; out="$(gen_settings "$2")" || { echo "    settings generation FAILED" >&2; return 1; }
  printf '%s' "$out" | jq -e . >/dev/null || { echo "    generated settings are not valid JSON" >&2; return 1; }
  if [ -f "$1" ] && ! diff -q <(jq -S . "$1" 2>/dev/null) <(printf '%s' "$out" | jq -S .) >/dev/null 2>&1; then
    cp "$1" "$1.bak.$(date +%Y%m%d%H%M%S)"
    echo "    backed up existing $(basename "$(dirname "$1")")/settings.json"
  fi
  printf '%s\n' "$out" > "$1"
}

write_settings "$P/settings.json" "$H/.config/claude/settings.personal.json"
write_settings "$R/settings.json" "$H/.config/claude/settings.reckit.json"

# Agents, skills and commands live once in the dotfiles and are symlinked into
# every profile. Looping over whatever exists (rather than naming each one)
# means adding a new agent or command needs no edit here — drop the file in
# ~/.config/claude/{agents,commands}/ or a dir in skills/ and re-run.
SRC="$H/.config/claude"
for prof in "$P" "$R"; do
  mkdir -p "$prof/agents" "$prof/skills" "$prof/commands"
  for f in "$SRC"/agents/*.md;   do [ -e "$f" ] && ln -sf  "$f" "$prof/agents/$(basename "$f")"; done
  for f in "$SRC"/commands/*.md; do [ -e "$f" ] && ln -sf  "$f" "$prof/commands/$(basename "$f")"; done
  for d in "$SRC"/skills/*/;     do [ -d "$d" ] && ln -sfn "${d%/}" "$prof/skills/$(basename "$d")"; done
done

echo "Bootstrapped Claude wiring for personal + reckit profiles."
echo "  agents:   $(ls -1 "$SRC"/agents/*.md 2>/dev/null | wc -l | tr -d ' ')"
echo "  commands: $(ls -1 "$SRC"/commands/*.md 2>/dev/null | wc -l | tr -d ' ')"
echo "  skills:   $(ls -1d "$SRC"/skills/*/ 2>/dev/null | wc -l | tr -d ' ')"
